---
title: "Untitled"
author: "Rb"
date: "20/2/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(countrycode)
library(janitor)
library(ggrepel)
```


```{r}
food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')
```

```{r}
emmission <- food_consumption %>% 
  group_by(country) %>% 
  mutate(total_emmission = sum(co2_emmission)) %>% 
  count(country, total_emmission) %>% 
  select(-n)
  
```


```{r}
asia_food_consumption <- food_consumption %>% 
  select(-co2_emmission) %>% 
  pivot_wider(names_from = food_category,
              values_from = consumption) %>%
  clean_names() %>% 
  mutate(continent = countrycode(country, origin = "country.name",
                                 destination = "continent")) %>% 
  filter(continent == "Asia") %>% 
  mutate(meat_products = pork + poultry + beef + lamb_goat + fish + eggs + milk_inc_cheese,
         vegetable_products = soybeans + nuts_inc_peanut_butter,
         protein_diet = meat_products + vegetable_products,
         carbohydrate_diet = wheat_and_wheat_products + rice) %>% 
  left_join(emmission, by = "country") %>% 
  mutate(carbohydrate_protein_ratio = carbohydrate_diet/protein_diet) %>%  select(country, carbohydrate_protein_ratio, total_emmission)
```

```{r}
plot <- asia_food_consumption %>% 
  ggplot(aes(carbohydrate_protein_ratio, total_emmission))+
  geom_point(aes(color = country)) +
  geom_text_repel(aes(label = country, family = "serif", fontface = "italic"),size = 3.5) +
  theme(axis.title = element_text(face = "bold"), legend.position = "none", panel.grid = element_blank(), 
        panel.background = element_rect(fill = "lemonchiffon1")) +
  labs(x = "Carbohydrate/Protein Ratio",
       y = "Total Carbon Emmission",
       title = "Diet and CO2 Emmission in Asia",
       subtitle = "The higher the ratio of carbohydrates and protein, the lower the carbon emissions",
       caption = "TidyTuesday week 8
       Source: nu3
       Article: r-tastic by Kasia Kulma
       Visualisation: @rubynciel")
```

